#!/bin/sh
#crear archivo segun el usu diga

filename="archivo_nuevo_vacio-$(date +%Y%m%d)"
username="$(whoami)"
echo -p "Digite en cuantos bytes quiere el fichero: "
read OBJETO 
echo "Digito $OBJ bytes"


sudo dd if=/home/$username/ |pv|dd of=$filename bs=$OBJ count=$OBJ
